#!/bin/bash
FILE="components/Sprint.jsx"
cp "$FILE" "$FILE.backup"
echo "Sauvegarde créée"
sed -i '' 's/COFFRE-FORT REPUTATIONNEL/COFFRE-FORT RÉPUTATIONNEL/g' "$FILE"
sed -i '' 's/Piliers Singularite/Piliers Singularité/g' "$FILE"
sed -i '' 's/Piliers de Singularite/Piliers de Singularité/g' "$FILE"
sed -i '' 's/Carte du Marche/Carte du Marché/g' "$FILE"
sed -i '' 's/REPONSES DE COMBAT/RÉPONSES DE COMBAT/g' "$FILE"
sed -i '' 's/MISSION ASSIGNEE/MISSION ASSIGNÉE/g' "$FILE"
sed -i '' 's/ELASTICITE DU MARCHE/ÉLASTICITÉ DU MARCHÉ/g' "$FILE"
sed -i '' 's/AUDIT DE CONTROLE/AUDIT DE CONTRÔLE/g' "$FILE"
sed -i '' 's/Extraction terminee/Extraction terminée/g' "$FILE"
sed -i '' 's/Sprint termine/Sprint terminé/g' "$FILE"
sed -i '' 's/APERCU/APERÇU/g' "$FILE"
sed -i '' 's/DENSITE/DENSITÉ/g' "$FILE"
sed -i '' 's/Densite atteinte/Densité atteinte/g' "$FILE"
sed -i '' 's/Ledger Reputation/Ledger Réputation/g' "$FILE"
sed -i '' "s/Aucune brique validee/Aucune brique validée/g" "$FILE"
sed -i '' "s/Script genere/Script généré/g" "$FILE"
sed -i '' "s/Generer/Générer/g" "$FILE"
sed -i '' "s/genere /généré /g" "$FILE"
sed -i '' "s/generee/générée/g" "$FILE"
sed -i '' "s/generees/générées/g" "$FILE"
sed -i '' "s/generer/générer/g" "$FILE"
sed -i '' "s/generes/générés/g" "$FILE"
sed -i '' "s/detecte /détecté /g" "$FILE"
sed -i '' "s/detectee/détectée/g" "$FILE"
sed -i '' "s/detectes /détectés /g" "$FILE"
sed -i '' "s/detecter/détecter/g" "$FILE"
sed -i '' "s/reponse/réponse/g" "$FILE"
sed -i '' "s/reponses/réponses/g" "$FILE"
sed -i '' "s/Reponds/Réponds/g" "$FILE"
sed -i '' "s/reponds/réponds/g" "$FILE"
sed -i '' "s/resultat/résultat/g" "$FILE"
sed -i '' "s/resultats/résultats/g" "$FILE"
sed -i '' "s/probleme/problème/g" "$FILE"
sed -i '' "s/problemes/problèmes/g" "$FILE"
sed -i '' "s/methode/méthode/g" "$FILE"
sed -i '' "s/competence/compétence/g" "$FILE"
sed -i '' "s/competences/compétences/g" "$FILE"
sed -i '' "s/experience/expérience/g" "$FILE"
sed -i '' "s/experiences/expériences/g" "$FILE"
sed -i '' "s/Experience/Expérience/g" "$FILE"
sed -i '' "s/realisation/réalisation/g" "$FILE"
sed -i '' "s/realisations/réalisations/g" "$FILE"
sed -i '' "s/negociation/négociation/g" "$FILE"
sed -i '' "s/negocier/négocier/g" "$FILE"
sed -i '' "s/carriere/carrière/g" "$FILE"
sed -i '' "s/elastique/élastique/g" "$FILE"
sed -i '' "s/elastiques/élastiques/g" "$FILE"
sed -i '' "s/elasticite/élasticité/g" "$FILE"
sed -i '' "s/densite/densité/g" "$FILE"
sed -i '' "s/maturite/maturité/g" "$FILE"
sed -i '' "s/Maturite/Maturité/g" "$FILE"
sed -i '' "s/singularite/singularité/g" "$FILE"
sed -i '' "s/Singularite/Singularité/g" "$FILE"
sed -i '' "s/rarete/rareté/g" "$FILE"
sed -i '' "s/specificite/spécificité/g" "$FILE"
sed -i '' "s/specifique/spécifique/g" "$FILE"
sed -i '' "s/specifiques/spécifiques/g" "$FILE"
sed -i '' "s/superieur/supérieur/g" "$FILE"
sed -i '' "s/superieure/supérieure/g" "$FILE"
sed -i '' "s/hierarchie/hiérarchie/g" "$FILE"
sed -i '' "s/hierarchique/hiérarchique/g" "$FILE"
sed -i '' "s/reecrit/réécrit/g" "$FILE"
sed -i '' "s/contexte marche/contexte marché/g" "$FILE"
sed -i '' "s/le marche/le marché/g" "$FILE"
sed -i '' "s/du marche/du marché/g" "$FILE"
sed -i '' "s/Marche elastique/Marché élastique/g" "$FILE"
sed -i '' "s/marche invisible/marché invisible/g" "$FILE"
sed -i '' "s/remede/remède/g" "$FILE"
sed -i '' "s/remedes/remèdes/g" "$FILE"
sed -i '' "s/resolu/résolu/g" "$FILE"
sed -i '' "s/resoudre/résoudre/g" "$FILE"
sed -i '' "s/reseau/réseau/g" "$FILE"
sed -i '' "s/reseaux/réseaux/g" "$FILE"
sed -i '' "s/reference/référence/g" "$FILE"
sed -i '' "s/references/références/g" "$FILE"
sed -i '' "s/decideur/décideur/g" "$FILE"
sed -i '' "s/decideurs/décideurs/g" "$FILE"
sed -i '' "s/deploiement/déploiement/g" "$FILE"
sed -i '' "s/deja /déjà /g" "$FILE"
sed -i '' "s/echec/échec/g" "$FILE"
sed -i '' "s/echoue/échoué/g" "$FILE"
sed -i '' "s/echouer/échouer/g" "$FILE"
sed -i '' "s/equipe/équipe/g" "$FILE"
sed -i '' "s/equipes/équipes/g" "$FILE"
sed -i '' "s/etape/étape/g" "$FILE"
sed -i '' "s/etapes/étapes/g" "$FILE"
sed -i '' "s/strategie/stratégie/g" "$FILE"
sed -i '' "s/strategique/stratégique/g" "$FILE"
sed -i '' "s/critere/critère/g" "$FILE"
sed -i '' "s/criteres/critères/g" "$FILE"
sed -i '' "s/derniere/dernière/g" "$FILE"
sed -i '' "s/premiere/première/g" "$FILE"
sed -i '' "s/matiere/matière/g" "$FILE"
sed -i '' "s/modele/modèle/g" "$FILE"
sed -i '' "s/systeme/système/g" "$FILE"
sed -i '' "s/systemes/systèmes/g" "$FILE"
sed -i '' "s/meme /même /g" "$FILE"
sed -i '' "s/empeche/empêche/g" "$FILE"
sed -i '' "s/empechent/empêchent/g" "$FILE"
sed -i '' "s/reconquete/reconquête/g" "$FILE"
sed -i '' "s/controle/contrôle/g" "$FILE"
sed -i '' "s/controler/contrôler/g" "$FILE"
sed -i '' "s/connait/connaît/g" "$FILE"
sed -i '' "s/apparait/apparaît/g" "$FILE"
sed -i '' "s/maitrise/maîtrise/g" "$FILE"
sed -i '' "s/recoit/reçoit/g" "$FILE"
sed -i '' "s/recoivent/reçoivent/g" "$FILE"
sed -i '' "s/lecon/leçon/g" "$FILE"
sed -i '' "s/facon/façon/g" "$FILE"
sed -i '' "s/francais/français/g" "$FILE"
sed -i '' "s/apercu/aperçu/g" "$FILE"
sed -i '' "s/annee/année/g" "$FILE"
sed -i '' "s/annees/années/g" "$FILE"
sed -i '' "s/donnees/données/g" "$FILE"
sed -i '' "s/entree/entrée/g" "$FILE"
sed -i '' "s/creation/création/g" "$FILE"
sed -i '' "s/verite/vérité/g" "$FILE"
sed -i '' "s/qualite/qualité/g" "$FILE"
sed -i '' "s/capacite/capacité/g" "$FILE"
sed -i '' "s/capacites/capacités/g" "$FILE"
sed -i '' "s/realite/réalité/g" "$FILE"
sed -i '' "s/credibilite/crédibilité/g" "$FILE"
sed -i '' "s/souverainete/souveraineté/g" "$FILE"
sed -i '' "s/visibilite/visibilité/g" "$FILE"
sed -i '' "s/stabilite/stabilité/g" "$FILE"
sed -i '' "s/vulnerabilite/vulnérabilité/g" "$FILE"
sed -i '' "s/efficacite/efficacité/g" "$FILE"
sed -i '' "s/regularite/régularité/g" "$FILE"
sed -i '' "s/categorie/catégorie/g" "$FILE"
sed -i '' "s/categories/catégories/g" "$FILE"
sed -i '' "s/periode/période/g" "$FILE"
sed -i '' "s/reussite/réussite/g" "$FILE"
sed -i '' "s/Reussite/Réussite/g" "$FILE"
sed -i '' "s/remuneration/rémunération/g" "$FILE"
sed -i '' "s/reflexe/réflexe/g" "$FILE"
sed -i '' "s/presence/présence/g" "$FILE"
sed -i '' "s/consequence/conséquence/g" "$FILE"
sed -i '' "s/frequence/fréquence/g" "$FILE"
sed -i '' "s/personnalisee/personnalisée/g" "$FILE"
sed -i '' "s/anonymisee/anonymisée/g" "$FILE"
sed -i '' "s/calibree/calibrée/g" "$FILE"
sed -i '' "s/structuree/structurée/g" "$FILE"
sed -i '' "s/documentee/documentée/g" "$FILE"
sed -i '' "s/documentes/documentés/g" "$FILE"
sed -i '' "s/terminee/terminée/g" "$FILE"
sed -i '' "s/Reduire/Réduire/g" "$FILE"
sed -i '' "s/epaissit/épaissit/g" "$FILE"
sed -i '' "s/elargit/élargit/g" "$FILE"
sed -i '' "s/evenement/événement/g" "$FILE"
sed -i '' "s/preparation/préparation/g" "$FILE"
sed -i '' "s/reputation/réputation/g" "$FILE"
sed -i '' "s/reputationnel/réputationnel/g" "$FILE"
sed -i '' "s/DECISION\"/DÉCISION\"/g" "$FILE"
sed -i '' "s/Marqueurs de decision/Marqueurs de décision/g" "$FILE"
sed -i '' "s/marqueurs de decision/marqueurs de décision/g" "$FILE"
sed -i '' "s/archivee/archivée/g" "$FILE"
sed -i '' "s/forgee/forgée/g" "$FILE"
sed -i '' "s/restructuree/restructurée/g" "$FILE"
sed -i '' "s/redigee/rédigée/g" "$FILE"
echo "Terminé. Pour annuler: cp $FILE.backup $FILE"
